# Generated by Django 2.2.6 on 2019-10-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('slack_ts', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('jira_issue', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=100)),
                ('requester', models.CharField(max_length=100)),
                ('executor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('project', models.CharField(max_length=10, unique=True)),
                ('issuetype', models.CharField(max_length=10)),
                ('priority', models.CharField(max_length=20)),
                ('id_tr_close', models.IntegerField(blank=True, null=True)),
                ('id_tr_reopen', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
