"""
Django settings for slackbot project.
Generated by 'django-admin startproject' using Django 2.2.6.
"""

import os
from decouple import config

# Base Directory
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1wa&*64kg9tw50*d*47cmt0wm1(dmlts)7@g5n1$t6nwc+ljlg'
ALLOWED_HOSTS = ['*']

# Application Definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'slackbot'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'slackbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'slackbot.wsgi.application'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Variáveis Gerais
SLACKBOT_DAEMON = config('SLACKBOT_DAEMON', 'false')
SLACKBOT_HOME = config('SLACKBOT_HOME', '/home/vinicius/Development/slackbot')

# Initial Configurations
DEFAULT_READ_DELAY = config('DEFAULT_READ_DELAY', 1)
DEFAULT_RETRY_DELAY = config('DEFAULT_RETRY_DELAY', 15)
DEFAULT_LOGLEVEL = config('DEFAULT_LOGLEVEL', 'DEEPDEBUG')

# Slack Configurations
SLACK_DOMAIN = config('SLACK_DOMAIN', '')
SLACK_TOKEN = config('SLACK_TOKEN', '')
SLACK_BOT_ID = config('SLACK_BOT_ID', '')
SLACK_CHANNEL = config('SLACK_CHANNEL', '')

# Jira Configurations
JIRA_SERVER = config('JIRA_SERVER', '')
JIRA_USER = config('JIRA_USER', '')
JIRA_PASSWORD = config('JIRA_PASSWORD', '')

# Echo Configurations
ECHO_STATUS = config('ECHO_STATUS', False)
ECHO_TARGET = config('ECHO_TARGET', '')
ECHO_SOURCE = config('ECHO_SOURCE', 'C1FUPUPSN,C4ZEWGV24,C5E6GNETV')

# Reactions
REACTION_SAD = config('REACTION_SAD', 'fire')
REACTION_SURPRISE = config('REACTION_SURPRISE', 'thinking_face')