"""
Django settings for slackbot project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from slackbot.settings.base import * # noqa
from decouple import config

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DATABASE_ENGINE = 'sqlite'
SQLITE_FILE = config('SQLITE_FILE', 'database.db')

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, SQLITE_FILE),
    }
}